### ISSUE TITLE
Отзыв на «Вложенные ссылки»

### ISSUE THREAD

**Issue by VovanR** [kizu/kizu.github.com#178]
Firefox, стоит плагин Flashblock; ссылка, обернутая в тэг `object` [не отображается](https://www.dropbox.com/s/l1h1hlto4xpsypg/Screenshot%20-%2003042015%20-%2011%3A45%3A09%20AM.png?dl=0)
Возможно какой-нибудь AdBlock тоже спрячет - я не знаю.

Вот правило, которое применяет Flashblock
```css
/*
 * Broken Objects.
*/
object
{ -moz-binding: url("chrome://flashblock/content/flashblock.xml#brokenobject") !important; }
```
