### ISSUE TITLE
Отзыв на «Новая версия этого сайта»

### ISSUE THREAD

**Issue by hudochenkov** [kizu/kizu.github.com#182]
Новая версия выглядит круто!

Как-то случайно в последнем Chrome на последней  Mac OS X вылезло такое:

![image](https://cloud.githubusercontent.com/assets/654597/17644689/00240466-6196-11e6-845f-b830ddabc655.png)

Я попытался разобраться куда добавить фикс, но как-то все очень сложно у тебя. Фикс простой: `@charset "utf-8";`.

А еще наблюдаются проблемы с рендерингом при прокрутке из-за фиксированных шапки и подвала. Фикс:

```css
.Page_post .Page-Header,
.Page_post .Page-Footer {
    will-change: opacity;
}
```
